/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airbosco_pyto.Vistas;

import airbosco_pyto.Controladores.Avion;
import airbosco_pyto.Controladores.Vuelo;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author danielblancoparla
 */
public class VueloAsignar extends javax.swing.JFrame {

    /**
     * Creates new form VueloAsignar
     */
    Vuelo vuelo = new Vuelo();
    Avion avion = new Avion();
    int modo = 0; // modo == 1 edicion
    int idVueloX = 0; // para almacenar el vuelo en caso de Editar

    public VueloAsignar() {
        initComponents();

        // Rellenamos Aviones
        ArrayList avionAr = avion.avionesArrayList();

        for (int i = 0; i < avionAr.size(); i++) {
            String[] resulAux = (String[]) avionAr.get(i);
            jComboAvion.addItem(resulAux[0]); // añadimos las matriculas solo
        }

        // Rellenamos minutos: 0 - 59m
        for (int i = 0; i < 60; i++) {
            jComboMinutos.addItem(i);
        }

        // Rellenamos dias: 0 - 31
        for (int i = 1; i < 32; i++) {
            jComboDia.addItem(i);
        }

        // Rellenamos meses: 1 - 12
        for (int i = 1; i < 13; i++) {
            jComboMes.addItem(i);
        }

        // Rellenamos rutas
        ArrayList rutasAr = vuelo.rutasListar();

        for (int i = 0; i < rutasAr.size(); i++) {
            String[] strAux = (String[]) rutasAr.get(i);
            String strAuxFinal = strAux[0] + " " + strAux[1] + " - " + strAux[2] + " " + strAux[3] + "'";
            jComboRuta.addItem(strAuxFinal);
        }

    }

    // CONSTRUCTOR PARA EDITAR
    public VueloAsignar(int idVuelo) {
        initComponents();

        // Cambiamos modo de edicion
        modo = 1;
        idVueloX = idVuelo;

        // Consultamos el vuelo con la idRuta pasada al constructor
        Object[] vueloAr = vuelo.consultarVuelo(idVuelo);

        jComboAvion.addItem(vueloAr[1]); // añadimos la matricula del avion
        jComboAvion.setEnabled(false); // No se puede desplegar

        Calendar fechaSalidaEditar = Calendar.getInstance();
        fechaSalidaEditar.setTimeInMillis((Long) vueloAr[0]);

        // Rellenamos Horas: 0 - 23
        for (int i = 0; i < 24; i++) {
            jComboHora.addItem(i);

            // Seleccionamos los minutos a editar
            if (fechaSalidaEditar.get(Calendar.HOUR_OF_DAY) == i) {
                jComboHora.setSelectedIndex(jComboHora.getItemCount() - 1);
            }

        }

        // Rellenamos minutos: 0 - 59m
        for (int i = 0; i < 60; i++) {
            jComboMinutos.addItem(i);

            // Seleccionamos los minutos a editar
            if (fechaSalidaEditar.get(Calendar.MINUTE) == i) {
                jComboMinutos.setSelectedIndex(jComboMinutos.getItemCount() - 1);
            }

        }

        // Rellenamos dias: 0 - 31
        for (int i = 1; i < 32; i++) {
            jComboDia.addItem(i);

            // Seleccionamos el dia a editar
            if (fechaSalidaEditar.get(Calendar.DAY_OF_MONTH) == i) {
                jComboDia.setSelectedIndex(jComboDia.getItemCount() - 1);
            }
        }

        // Rellenamos meses: 1 - 12
        for (int i = 1; i < 13; i++) {
            jComboMes.addItem(i);

            // Seleccionamos el mes a editar
            if (fechaSalidaEditar.get(Calendar.MONTH) == i) {
                jComboMes.setSelectedIndex(jComboMes.getItemCount() - 1);
            }
        }

        // Rellenamos rutas
        ArrayList rutasAr = vuelo.rutasListar();

        for (int i = 0; i < rutasAr.size(); i++) {
            String[] strAux = (String[]) rutasAr.get(i);
            String strAuxFinal = strAux[0] + " " + strAux[1] + " - " + strAux[2] + " " + strAux[3] + "'";
            jComboRuta.addItem(strAuxFinal);

            // Para dejar selecciona la ruta del vuelo
            if (strAux[0].equals(Integer.toString((int) vueloAr[2]))) {
                // Restamos 1 por que la posicion 1 es == 0!
                jComboRuta.setSelectedIndex(jComboRuta.getItemCount() - 1);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboRuta = new javax.swing.JComboBox();
        jComboDia = new javax.swing.JComboBox();
        jComboMes = new javax.swing.JComboBox();
        jTextFieldAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboHora = new javax.swing.JComboBox();
        jComboMinutos = new javax.swing.JComboBox();
        jComboAvion = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Vuelo-Ruta");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Avión");

        jLabel2.setText("Fecha Salida");

        jLabel3.setText("Ruta");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldAno.setText("2015");

        jLabel4.setText("Hora Salida");

        jLabel5.setText(":");

        jLabel6.setText("/");

        jLabel7.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboMinutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addComponent(jComboAvion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jComboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // Para convertir la fecha a Long
        Calendar fechaSalida = Calendar.getInstance();

        // fijamos la fecha introducida por el usuario 
        fechaSalida.set(Integer.parseInt(jTextFieldAno.getText()), Integer.parseInt(jComboMes.getSelectedItem().toString()),
                Integer.parseInt(jComboDia.getSelectedItem().toString()), Integer.parseInt(jComboHora.getSelectedItem().toString()),
                Integer.parseInt(jComboMinutos.getSelectedItem().toString()));

        // Sacamos la idRuta del Vuelo
        ArrayList rutasAr = vuelo.rutasListar();
        String[] idRutaRow = (String[]) rutasAr.get(jComboRuta.getSelectedIndex());
        int idRuta = Integer.parseInt(idRutaRow[0]);

        if (modo == 0) {
            // Finalmente lo guardamos        
            vuelo.guardarVuelo(jComboAvion.getSelectedItem().toString(), idRuta, fechaSalida.getTime().getTime());
        } else if (modo == 1) {
            // O lo actualizamos
            vuelo.actualizarVuelo(idVueloX, idRuta, fechaSalida.getTime().getTime());
        }

        this.dispose(); // Cerramos la ventana
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueloAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueloAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueloAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueloAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueloAsignar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboAvion;
    private javax.swing.JComboBox jComboDia;
    private javax.swing.JComboBox jComboHora;
    private javax.swing.JComboBox jComboMes;
    private javax.swing.JComboBox jComboMinutos;
    private javax.swing.JComboBox jComboRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldAno;
    // End of variables declaration//GEN-END:variables
}
