/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airbosco_pyto.Vistas;

import airbosco_pyto.Controladores.Avion;
import airbosco_pyto.Controladores.Vuelo;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danielblancoparla
 */
public class VueloMain extends javax.swing.JFrame {

    Avion avion = null;
    Vuelo vuelo = null;

    DefaultListModel listModel = new DefaultListModel(); // Lista pestaña Consultar

    String[] columnas = {"ID Vuelo", "Origen", "Destino", "Fecha Salida", "Fecha Llegada", "Duración Viaje"};
    DefaultTableModel tableModel = new DefaultTableModel(columnas, 0);

    String[] columnasRutas = {"Identificador", "Origen", "Destino", "Duración"};
    DefaultTableModel tableRutasModel = new DefaultTableModel(columnasRutas, 0); // Tabla pestaña Rutas

    /**
     * Creates new form VueloMain
     */
    public VueloMain() {
        vuelo = new Vuelo();
        avion = new Avion();

        initComponents();

        // CONSULTAR
        listModel.addElement("TODOS"); // Para mostrar todos los vuelos
        rellenarjList(listModel, avion.avionesArrayList()); // Rellenamos lista con aviones
        jListAviones.setSelectedIndex(0); // Dejamos TODOS marcados por defecto 

        // RUTAS
        actualizarTablaRutas(); // Rellenamos lista con las rutas

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rutasAvion = new javax.swing.JTabbedPane();
        consultar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAviones = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableConsultar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rutas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRutas = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Vuelos");
        setResizable(false);

        rutasAvion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutasAvionFocusGained(evt);
            }
        });

        jLabel1.setText("Selecciona un avión:");

        jListAviones.setModel(listModel);
        jListAviones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAvionesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListAviones);

        jLabel2.setText("Vuelos programados:");

        tableConsultar.setAutoCreateRowSorter(true);
        tableConsultar.setModel(tableModel);
        tableConsultar.setShowGrid(false);
        tableConsultar.setShowHorizontalLines(true);
        tableConsultar.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tableConsultar);

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        rutasAvion.addTab("Consultar", consultar);

        jLabel3.setText("Rutas actuales:");

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        tableRutas.setModel(tableRutasModel);
        jScrollPane4.setViewportView(tableRutas);

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Refrescar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rutasLayout = new javax.swing.GroupLayout(rutas);
        rutas.setLayout(rutasLayout);
        rutasLayout.setHorizontalGroup(
            rutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(rutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rutasLayout.setVerticalGroup(
            rutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(rutasLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(4, 4, 4)
                        .addComponent(editarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarButton)
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );

        rutasAvion.addTab("Rutas", rutas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rutasAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rutasAvion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Boton de borrar
        vuelo.borrarVuelo(Integer.parseInt(tableConsultar.getValueAt(tableConsultar.getSelectedRow(), 0).toString()));
        
        // actualizamos tabla
        while (tableModel.getRowCount() != 0) {
            tableModel.removeRow(0); // Borramos contenido tabla
        }
        actualizarTablaVuelos(jListAviones.getSelectedValue().toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jListAvionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAvionesValueChanged
        // TODO add your handling code here:
        while (tableModel.getRowCount() != 0) {
            tableModel.removeRow(0); // Borramos contenido tabla
        }
        actualizarTablaVuelos(jListAviones.getSelectedValue().toString());
    }//GEN-LAST:event_jListAvionesValueChanged

    private void rutasAvionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutasAvionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rutasAvionFocusGained

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:

        String[] arrayRuta = {(String) tableRutas.getValueAt(tableRutas.getSelectedRow(), 0),
            (String) tableRutas.getValueAt(tableRutas.getSelectedRow(), 1),
            (String) tableRutas.getValueAt(tableRutas.getSelectedRow(), 2),
            (String) tableRutas.getValueAt(tableRutas.getSelectedRow(), 3),};

        VueloRutaCrear vrc = new VueloRutaCrear(arrayRuta);
        vrc.setVisible(true);
    }//GEN-LAST:event_editarButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        while (tableRutasModel.getRowCount() != 0) {
            tableRutasModel.removeRow(0);
        }
        actualizarTablaRutas();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VueloRutaCrear vrc = new VueloRutaCrear();
        vrc.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        // TODO add your handling code here:
        vuelo.eliminarRuta(Integer.parseInt((String) tableRutas.getValueAt(tableRutas.getSelectedRow(), 0)));
        
        // actualizamos tabla rutas
        while (tableRutasModel.getRowCount() != 0) {
            tableRutasModel.removeRow(0);
        }
        actualizarTablaRutas();
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VueloAsignar va = new VueloAsignar();
        va.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Editar Vuelo-Ruta
        int idRutaA = Integer.parseInt((String) tableConsultar.getValueAt(tableConsultar.getSelectedRow(), 0));
        VueloAsignar va = new VueloAsignar(idRutaA);
        va.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueloMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueloMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueloMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueloMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueloMain().setVisible(true);
            }
        });
    }

    public void rellenarjList(DefaultListModel dfm, ArrayList axal) {

        for (int i = 0; i < axal.size(); i++) {
            String[] resulAux = (String[]) axal.get(i);
            dfm.addElement(resulAux[0]);
        }

    }

    public void actualizarTablaVuelos(String matricula) {
        ArrayList rVuelos = vuelo.vueloAvionArrayList(matricula);

        for (int i = 0; i < rVuelos.size(); i++) {
            String[] resultAvion = (String[]) rVuelos.get(i);
            insertarjTableAvion(resultAvion[0], resultAvion[1], resultAvion[2], resultAvion[3], resultAvion[4], resultAvion[5]);
        }

    }

    // RUTAS
    public void actualizarTablaRutas() {
        ArrayList arRutas = vuelo.rutasListar();

        for (int i = 0; i < arRutas.size(); i++) {
            String[] resultRuta = (String[]) arRutas.get(i);
            tableRutasModel.addRow(resultRuta);
        }

    }

    public void actualizarFieldsRutas(int idRuta) {

    }

    // Clases AUXILIARES para tratar los datos de las tablas
    public void insertarjTableAvion(String idVuelo, String origen, String destino, String fechaSalida, String matriculaAvion, String duracion) {

        Date fechaSalidaString = new Date(Long.valueOf(fechaSalida)); // Para convertir la fecha a formato legible
        Date fechaLlegada = sumarMinutosFechaLlegada(Integer.parseInt(duracion), Long.valueOf(fechaSalida));

        tableModel.addRow(new Object[]{idVuelo, origen, destino, fechaSalidaString.toString(), fechaLlegada.toString(), duracion + "'"});
    }

    public Date sumarMinutosFechaLlegada(int minutos, long fechaSalida) {
        long UN_MINUTO_MS = 60000; // milisegundos

        Date calculada = new Date(fechaSalida + minutos * UN_MINUTO_MS);

        return calculada;
    }

    public JTable getTableRutas() {
        return tableRutas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarButton;
    private javax.swing.JPanel consultar;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListAviones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel rutas;
    private javax.swing.JTabbedPane rutasAvion;
    private javax.swing.JTable tableConsultar;
    private javax.swing.JTable tableRutas;
    // End of variables declaration//GEN-END:variables
}
